### ISSUE TITLE
中文字体可以考虑鸿蒙字体

### ISSUE THREAD

**Issue by OrionLi** [AirLongDian/MeowSans_Font#6]
中文字体改为[Harmony OS Sans SC](https://developer.huawei.com/consumer/cn/design/resource)可能显示效果更佳

**Comment by AirLongDian** [comment]
该字体是否可以二次分发？

**Comment by OrionLi** [comment]
> 该字体是否可以二次分发？

刚去看了看，好像不行，那还是算了吧
